version: '3.9'
services:
  frontend:
    image: tmbster-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:80"
  backend:
    image: tmbster-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"